name: Node.js Bot

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *' # every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Start
        run: npm start
        env:
          CI: false
          USER: ${{secrets.USER_NAME}}
          PASSWORD: ${{secrets.PASSWORD}}
          PAGE_HANDLES: ${{secrets.PAGE_HANDLES}}
